name: Manual upgrade

on: 
  workflow_dispatch:
    inputs:
      directory:
        description: 'Environment to deploy. The following path will prefix the folder name: environments/'
        required: true
        type: string

jobs:
    helm_deploy:
        name: Helm deploy
        runs-on: [self-hosted,  base-runners ]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: azure/setup-helm@v3
              with:
                 version: 'v3.2.1'
              id: install_helm
            - name: helm deploy
              env:
                values_file: "environments/${{ inputs.directory }}/values.yaml"
              run: |
                helm upgrade -n default ${{ inputs.directory }} --install --wait './helm_chart' -f $values_file
 
